SRE-2998 - Adding common label for grabbing grafana dashboards
Bluescape/helm pull request #131
Opened 2023-11-06 20:21 UTC by sivakathali

2023-11-07 11:47 UTC, ashwinrajadurai3 requested changes

2023-11-07 11:47 UTC, ashwinrajadurai3 commented on charts/bluescape-banzai-dashboards/Chart.yaml
> +version: 0.1.3-alpha
Not here

2023-11-07 11:47 UTC, ashwinrajadurai3 commented on charts/bluescape-monitoring-dashboards/Chart.yaml
> +version: 0.3.27-alpha
This alone works

2023-11-07 11:49 UTC, sivakathali commented on charts/bluescape-banzai-dashboards/Chart.yaml
> +version: 0.1.3-alpha
But in this chart also we made changes

2023-11-07 11:52 UTC, ashwinrajadurai3 requested changes

2023-11-07 11:52 UTC, ashwinrajadurai3 commented on charts/bluescape-banzai-dashboards/Chart.yaml
> +version: 0.1.3-alpha
That's fine, this isn't referenced in infra repo

2023-11-07 14:26 UTC, notjames submitted a review, later dismissed
please see comments in https://github.com/Bluescape/infrastructure/pull/7216

2023-11-08 15:38 UTC, alexeyatbluescape approved these changes
LGTM!

2023-11-09 16:15 UTC, ashwinrajadurai3 approved these changes

2023-11-09 16:21 UTC, ashwinrajadurai3 approved these changes
LGTM

2023-11-09 20:15 UTC, merged