SRE-2998 - Siva - Refactoring add-dashboard script to use multiple da…
Bluescape/helm pull request #134
Opened 2023-11-27 11:31 UTC by sivakathali

…shboard bases & helm releases

2023-11-27 13:37 UTC, notjames requested changes
things to consider. see comments.

2023-11-27 13:37 UTC, notjames commented on bin/generate-dashboard
> +    l) echo "Available dashboard bases
This doesn't scale. We need to engineer a scalable solution. One possible, though not elegant method, would be to do something like:

```
available_dashboards=($dashboard_base/*)

while getops "..." opt; do
  case $opt in
    ...
    l) echo "Available dashboard directories (bases) are:"
       for b in "${available_dashboards[@]}";do echo ${b##*/};done
    ;;
    ...
  esac
done
```

variable placement location will be important in this example. The variable will need to be declared before using it in the `-l|--list` (recommend using long opts as well, btw) because otherwise this wouldn't work.

Also, please keep bracing consistent in the script (see `usage() {` vs `usage()\n{`).

2023-11-27 13:37 UTC, notjames commented on bin/generate-dashboard
> +fi
this logic is flawed. There is absolutely no need to `elif` this. In fact, it's almost always better to fast-fail than to `else` or `elif` conditionals for readability.

You almost got it right. This block can be written:
```
if [ -z "$dashboard_base" ]; then
  echo >&2 "Error: Dashboard base path (-b) is required, use add-dasbhoard -l to get list of available dashboard base"
  usage
  exit 1
fi

if [[ ! " ${available_dashboards[@]} " =~ " ${dashboard_base} " ]]; then
  echo >&2 """
Error: Specified dashboard base '$dashboard_base' is not in the list of available dashboards.
Available dashboard bases: ${available_dashboards[*]}
"""
  usage
  exit 1
fi
```

2023-11-27 13:37 UTC, notjames commented on bin/generate-dashboard
> +IFS=/ read -ra DIRS <<< "$dashboard_base"
I don't remember if this is something that was in the original script or something that is new, however, it's possible that you should combine this logic with my earlier suggestion (`available_dashboards=($dashboard_base/*)`) and test it out. Meaning that you might want to use `$DIRS` in my earlier suggestion vs what I stated, or use what I stated in the suggestion in the rest of the script. Your call. I haven't verified or checked it. Let me know if this comment makes sense. The main point is that you want to use one pragma and stick with it.

2023-11-27 23:38 UTC, sivakathali commented on bin/generate-dashboard
> +    l) echo "Available dashboard bases
As SRE should have control on dashboard base directories, kept these in array , also to make use of dashboard base there are some mandatory files/folders like templates/0_template, Charts.yaml etc., should be maintainted. which SRE only can do it. so in future if someone try to use unavailable dashboard base it throws error. Please refer the latest code

2023-11-27 23:39 UTC, sivakathali commented on bin/generate-dashboard
> +fi
Removed this in the latest code

2023-11-27 23:40 UTC, sivakathali commented on bin/generate-dashboard
> +IFS=/ read -ra DIRS <<< "$dashboard_base"
yes, not required as I changed the logic to use the script execution from charts instead existing charts/bluescape-monitoring-dashboards

2023-12-19 05:18 UTC, notjames requested changes
Things to be discussed or addressed...

2023-12-19 05:18 UTC, notjames commented on bin/generate-dashboard
> +done
The pattern we've already established is shift 1, assign, and have a global shift behind the case statement. Please follow the established pattern.

```
ADB='bluescape-monitoring-dashboards'

while [[ $# -gt 0 ]]; do
  case "$1" in
    -j|--json)
      shift
      to_add="$1"
      ;;
    -d|--dir)
      shift
      new_dashboard_dir="$1"
      ;;
    -b|--base)
      shift
      dashboard_base="$1"
      ;;
    -h|--help)
      usage
      ;;
    -l|--list)
      echo "Available dashboard bases "
      ls ${ADB}*
      exit 0
      ;;
    *)
      echo "Invalid option: $1" >&2
      exit 1
      ;;
  esac
  shift
done
```

I'd also prefer NOT to hard-code any dashboard directories. I understand what you're trying to do but the reason you articulate doesn't outweigh the extra work to manage the script if we add a directory. If someone adds a directory, it doesn't cause any problems for loading dashboards. Moreover, if someone has to add an additional directory, it's much easier for an SRE to add the extra directories only than to do all that work *and* fix the script. There are better ways to do this whole thing, but let's not worry about that right now. Let's just make sure this is scalable.

2023-12-19 05:18 UTC, notjames commented on bin/generate-dashboard
> +  done
using my sample code above, the following would need to be changed:

```
if [[ -d "$dashboard_base" ]]; then
  found_dashboard_base=true
fi
```

2023-12-22 18:26 UTC, notjames approved these changes
lgtm

2023-12-25 11:03 UTC, merged